// Generated by MistCSS, do not modify
import './index.mist.css'

import type { JSX, ReactNode } from 'react'

type RatioProps = {
  children?: ReactNode
} & JSX.IntrinsicElements['div']

export function Ratio({ children, ...props }: RatioProps) {
  return (
    <div {...props} className="ratio">
      {children}
    </div>
  )
}
