// Generated by MistCSS, do not modify
import "./index.mist.css";

import type { JSX, ReactNode } from "react";

type RatioProps = JSX.IntrinsicElements["div"] &
  Readonly<{
    children?: ReactNode;
  }>;

export const Ratio = ({ children, ...props }: RatioProps) => (
  <div {...props} className="ratio">
    {children}
  </div>
);
