// Generated by MistCSS, do not modify
import "./index.mist.css";

import type { JSX, ReactNode } from "react";

type ButtonProps = JSX.IntrinsicElements["button"] &
  Readonly<{
    children?: ReactNode;
    variant?: "danger" | "info" | "success" | "warning";
  }>;

export const Button = ({ children, variant, ...props }: ButtonProps) => (
  <button {...props} className="button" data-variant={variant}>
    {children}
  </button>
);
