// Generated by MistCSS, do not modify
import './index.mist.css'

import type { JSX, ReactNode } from 'react'

type DividerProps = {
  children?: ReactNode
} & JSX.IntrinsicElements['hr']

export function Divider({ children, ...props }: DividerProps) {
  return (
    <hr {...props} className="divider">
      {children}
    </hr>
  )
}
