// Generated by MistCSS, do not modify
import "./index.mist.css";

import type { JSX, ReactNode } from "react";

type CellProps = JSX.IntrinsicElements["div"] &
  Readonly<{
    children?: ReactNode;
    columns?:
      | "1"
      | "2"
      | "3"
      | "4"
      | "5"
      | "6"
      | "7"
      | "8"
      | "9"
      | "10"
      | "11"
      | "12";
    rows?:
      | "1"
      | "2"
      | "3"
      | "4"
      | "5"
      | "6"
      | "7"
      | "8"
      | "9"
      | "10"
      | "11"
      | "12";
  }>;

export const Cell = ({ children, columns, rows, ...props }: CellProps) => (
  <div {...props} className="cell" data-columns={columns} data-rows={rows}>
    {children}
  </div>
);

type GridProps = JSX.IntrinsicElements["div"] &
  Readonly<{
    children?: ReactNode;
    columns?:
      | "1"
      | "2"
      | "3"
      | "4"
      | "5"
      | "6"
      | "7"
      | "8"
      | "9"
      | "10"
      | "11"
      | "12";
    rows?:
      | "1"
      | "2"
      | "3"
      | "4"
      | "5"
      | "6"
      | "7"
      | "8"
      | "9"
      | "10"
      | "11"
      | "12";
  }>;

export const Grid = ({ children, columns, rows, ...props }: GridProps) => (
  <div {...props} className="grid" data-columns={columns} data-rows={rows}>
    {children}
  </div>
);
