// Generated by MistCSS, do not modify
import './index.mist.css'

import type { JSX, ReactNode } from 'react'

type CellProps = {
  children?: ReactNode
} & JSX.IntrinsicElements['div']

export function Cell({ children, ...props }: CellProps) {
  return (
    <div {...props} className="cell">
      {children}
    </div>
  )
}

type GridProps = {
  children?: ReactNode
} & JSX.IntrinsicElements['div']

export function Grid({ children, ...props }: GridProps) {
  return (
    <div {...props} className="grid">
      {children}
    </div>
  )
}
