// Generated by MistCSS, do not modify
import './index.mist.css'

type FlexProps = {
  children?: React.ReactNode
  direction?: 'row' | 'row-reverse' | 'col-reverse'
  justify?: 'start' | 'end' | 'center' | 'between' | 'around'
  items?: 'start' | 'end' | 'center' | 'baseline' | 'stretch'
  content?: 'start' | 'end' | 'center' | 'between' | 'around' | 'stretch'
  gap?: '0' | '1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9' | '10' | '11' | '12' | '14' | '16' | '20' | '24' | '28' | '32' | '36' | '40'
} & JSX.IntrinsicElements['div']

export function Flex({ children, direction, justify, items, content, gap, ...props }: FlexProps) {
  return (
    <div {...props} className="flex" data-direction={direction} data-justify={justify} data-items={items} data-content={content} data-gap={gap}>
      {children}
    </div>
  )
}
