// Generated by MistCSS, do not modify
import "./index.mist.css";

import type { JSX, ReactNode } from "react";

type FlexProps = JSX.IntrinsicElements["div"] &
  Readonly<{
    children?: ReactNode;
    content?: "around" | "between" | "center" | "end" | "start" | "stretch";
    direction?: "col-reverse" | "row-reverse" | "row";
    gap?:
      | "0"
      | "1"
      | "2"
      | "3"
      | "4"
      | "5"
      | "6"
      | "7"
      | "8"
      | "9"
      | "10"
      | "11"
      | "12"
      | "14"
      | "16"
      | "20"
      | "24"
      | "28"
      | "32"
      | "36"
      | "40";
    items?: "baseline" | "center" | "end" | "start" | "stretch";
    justify?: "around" | "between" | "center" | "end" | "start";
  }>;

export const Flex = ({
  children,
  content,
  direction,
  gap,
  items,
  justify,
  ...props
}: FlexProps) => (
  <div
    {...props}
    className="flex"
    data-content={content}
    data-direction={direction}
    data-gap={gap}
    data-items={items}
    data-justify={justify}
  >
    {children}
  </div>
);
