// Generated by MistCSS, do not modify
import './index.mist.css'

type ButtongroupProps = {
  children?: React.ReactNode
} & JSX.IntrinsicElements['div']

export function Buttongroup({ children, ...props }: ButtongroupProps) {
  return (
    <div {...props} className="buttongroup">
      {children}
    </div>
  )
}
