// Generated by MistCSS, do not modify
import "./index.mist.css";

import type { JSX, ReactNode } from "react";

type ButtonGroupProps = JSX.IntrinsicElements["div"] &
  Readonly<{
    children?: ReactNode;
    size?: "lg" | "sm";
  }>;

export const ButtonGroup = ({ children, size, ...props }: ButtonGroupProps) => (
  <div {...props} className="button-group" data-size={size}>
    {children}
  </div>
);
