// Generated by MistCSS, do not modify
import './index.mist.css'

type ButtonGroupProps = {
  children?: React.ReactNode
} & JSX.IntrinsicElements['div']

export function ButtonGroup({ children, ...props }: ButtonGroupProps) {
  return (
    <div {...props} className="button-group">
      {children}
    </div>
  )
}
