// Generated by MistCSS, do not modify
import './index.mist.css'

import type { JSX, ReactNode } from 'react'

type BoxProps = {
  children?: ReactNode
  size?: 'xs' | 'md' | 'lg'
} & JSX.IntrinsicElements['div']

export function Box({ children, size, ...props }: BoxProps) {
  return (
    <div {...props} className="box" data-size={size}>
      {children}
    </div>
  )
}
