// Generated by MistCSS, do not modify
import "./index.mist.css";

type BoxProps = JSX.IntrinsicElements["div"] &
  Readonly<{
    children?: React.ReactNode;
    size?: "lg" | "md";
  }>;

export const Box = ({ children, size, ...props }: BoxProps) => (
  <div {...props} className="box" data-size={size}>
    {children}
  </div>
);
