// Generated by MistCSS, do not modify
import "./index.mist.css";

import type { JSX, ReactNode } from "react";

type BoxProps = JSX.IntrinsicElements["div"] &
  Readonly<{
    children?: ReactNode;
    size?: "lg" | "md" | "xs";
  }>;

export const Box = ({ children, size, ...props }: BoxProps) => (
  <div {...props} className="box" data-size={size}>
    {children}
  </div>
);
